name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/my-image-name:$(date +%s) \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/my-image-name:latest

      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/bkimage --all-tags

      - name: Run the Docker image
        run: |
          docker run -d \
            --name bkapp \
            -p 5000:5000 \
            ${{ secrets.DOCKERHUB_USERNAME }}/bkimages:latest

      - name: Verify container is running
        run: |
          docker ps
          curl --retry 5 --retry-delay 3 http://localhost:5000
